version: '3.3'
services:
  back:
    container_name: usermanagement-back
    image: openjdk:17
    volumes:
      - ./:/usermanagement
    ports:
      - "8080:8080"
    links:
      - db
    working_dir: /usermanagement
    command: ./mvnw spring-boot:run
  db:
    container_name: usermanagement-db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'db-admin'
    ports:
      - '3316:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: